name: heytea_env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - customtkinter==5.2.2
    - opencv-python==4.8.1.78
    - numpy==1.24.3
    - pillow==10.1.0
    - torch==2.1.0
    - torchvision==0.16.0
    - scipy==1.11.4
    - pydirectinput==1.0.4
    - pynput==1.7.6
    - keyboard==0.13.5
